### ISSUE TITLE
[Source Request] MangaHub

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/extensions#105]
I'd like it if [Mangahub](https://mangahub.io) was a source because it updates **much** faster than other sources I've used on Paperback.

I hope I did correctly I sorry plz forgive plz :(

**Comment by ConradWeiser** [comment]
Yeah, I can probably do this one. I'll add it to the todo list.

**Comment by ConradWeiser** [comment]
After some discussion with Paper, it seems like MangaHub has some content locked behind an account sign-in. (For instance, you cannot read One Piece unless you sign into the website)

This causes some difficulties when it comes to implementing the source into an application. If Paperback ever supports that feature, perhaps MangaHub will be considered. Until then, I think this one needs to go on the backburner for now.
