### ISSUE TITLE
[Bug] MangaFox has infinite load of chapters for some manga

### ISSUE THREAD

**Issue by HellDuke-Astaroth** [Paperback-iOS/extensions#38]
The manga shown below shows under MangaFox Source, but the chapter list never actually loads.

![image](https://user-images.githubusercontent.com/58122642/82621261-997ae300-9ba8-11ea-9894-8fd55c4c56c1.png)

**Comment by Sirush** [comment]
Should be fixed in #40

**Comment by ConradWeiser** [comment]
Validated!
