### ISSUE TITLE
[Bug] Source POST bodies not being applied correctly

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/extensions#55]
For the EHentai source, some of the requests are to be made POST with a raw body.
An example of such looks like the following:

`{
	"method": "gdata",
	"gidlist": [
		[1645589, "1f3e7c0ead"]
	],
	"namespace": 1
}`

The body is being appended to the Request object's 'data' field.
Despite being a valid URL, and Body, the app always returns undefined however.

Does Paperback handle this currently?

**Comment by ConradWeiser** [comment]
Note that this passes unit tests, the application is behaving differently than the dev-enviroment.

**Comment by ConradWeiser** [comment]
Relevant method implemented in the source. The structure of data is verified to be correct.

```  getMangaDetailsRequest(ids: string[]): Request[] {
    let requests: Request[] = []
    for (let id of ids) {

      // Generate a proper json structure for this request
      let data = {
        method: "gdata",
        gidlist: [[Number(id.substr(0, id.indexOf("/"))), id.substr(id.indexOf("/") + 1, id.length)]],
        namespace: 1
      }

      let metadata = { 'id': id }
      requests.push(createRequestObject({
        url: `${E_API}`,
        metadata: metadata,
        method: 'POST',
        data: JSON.stringify(data)
      }))
    }
    return requests
  }```

**Comment by FaizanDurrani** [comment]
You need to set the content-type header to application/json, the can’t implicitly tell what you’re trying to send in the data field.

**Comment by ConradWeiser** [comment]
Both Accepts and content-type have been appended to the request, and the bug still continues to persist.

**Comment by ConradWeiser** [comment]
Proven to not be a problem with the app
