### ISSUE TITLE
[Source Request] Manhwa (manhwa.club)

### ISSUE THREAD

**Issue by Fluffl25** [Paperback-iOS/extensions#61]
Not entirely sure if this is the correct place the post such a request, so apologies in advanced. 
I would like to request a manhwa source such as 
- manhwa.club

This source covers both manhwa which aren't on others as well as a few 18+ ones I believe.
To my knowledge this is a madara source so theoretically this wouldn't take long to add?

Thanks for hearing me out, and hopefully you guys can add this :D.

**Comment by Fluffl25** [comment]
Discord - Fluffl25#7281

Thanks so much

**Comment by Butters831** [comment]
Id also love this feature but for a diffrent manhwa site manhwa18.com /manhwa18.net.  Even if you decide not to support these sites id also like to be updated my discord username : butters#8923

Thank you @ConradWeiser

**Comment by ConradWeiser** [comment]
@Butters831 Can you determine if there is much overlap between manhwa.club and your manhwa18 websites? If they are mostly the same, I don't think I will implement both. But if one has a lot of content which the other doesn't have, I'd be more than happy to put it in!

**Comment by Fluffl25** [comment]
I just had a look and for the most part there's a pretty big overlap. Manhwa18 is purely 18+ content hence the 18 in the name whereas ManhwaClub has some other non 18 manhwa (minimal). That said Manwha18 also has RAW manhwa meaning they're still in korean. Personally I think only one needs to be added, and either or should do.

**Comment by ConradWeiser** [comment]
I'll leave things to you two, then. Determine which one you'd like, and I'll make sure it'll get implemented.
I had to do ManhwaClub from scratch anyways, so I'm only a few functions in. It's no bother to me if you two decide that Manhwa18 is a better option.

**Comment by Butters831** [comment]
Correct manhwa18 has mostly purly 18+ content, its one of the best sites (in my opinion) since they update with raws and subs daily. Manhwaclub has a mixture of both but has less updates through the month.

**Comment by ConradWeiser** [comment]
Also, note if either of the websites are blocked in certain countries. If so, I'll plan on implementing a redirector version to get around those blocks.
Thanks!

**Comment by Fluffl25** [comment]
I honestly dont mind, so Ill leave Butters831 with this. Thanks for your hard work!

**Comment by ConradWeiser** [comment]
Alright, Manhwa18 it is. Stay tuned! I'll aim to release a beta in a few hours.

**Comment by ConradWeiser** [comment]
@Butters831 @Fluffl25 Alright, most of Manga18's functionality is completed. I'm likely going to push it out for validation on the app shortly.

One of the key features which is missing right now, is the home page contents. 
I'd like the both of your opinions. What would you like to see on the home page for this source? The website has the following sections:

Popular Manhwa (Note that this section DOES have duplicates. This can be filtered I guess(?))
Latest Raws (Not english)
Completed Manhwas (Self explanitory)

This is the sections you would get if you parsed the main screen.
Optionally, there's another page which can be displayed on the app home-section. If you navigate to the [Manhwa List](https://manhwa18.com/manga-list-genre-manhwa.html), a more static, but more relevent(?) list could be displayed instead. 

What do you think?

**Comment by Fluffl25** [comment]
From my perspective, Latest Raws and Completed Manhwas would have the least mass appeal. This leaves Popular Manhwa's and Manhwa List. Considering there are duplicates, by process of elimination this leaves Manhwa List to be the best option. After having a closer look, Manhwa List seems to default to most viewed Manhwa, which isn't inherently bad and is a decent compromise for a popularity measure. Im not all too familiar with what should and shouldn't be displayed, but if it were up to me, it would either be "Popular Manhwa" or "Manhwa List". @Butters831 will likely have better insight regarding this matter.

**Comment by Butters831** [comment]
Id personally suggest latest raws. The title actually dosent seem as it appears. The “ latest raws “ section serves as a hub for all their updated manhwas. They post both english subbed and raw links under that subsection

**Comment by ConradWeiser** [comment]
On second look, you'd be correct! I didn't notice that the 'Latest Raws' section has more than just RAW types. 
I'll aim for that, then. Thanks for the feedback!

**Comment by ConradWeiser** [comment]
Alright, a Beta is released at the moment. In theory it all should be working, although opening up a chapter causes a crash.
I cannot determine what the crash cause is, as the source log doesn't really seem to show anything abnormal. Will continue to investigate.

**Comment by ConradWeiser** [comment]
Crashes have been fixed.
There are some bugs which needs worked out (such as language flags) but it's in a usable state at the moment. Updates will come in over time, cleaning it up!

**Comment by Butters831** [comment]
Thank you
