### ISSUE TITLE
[Source Request] ReadComicOnline

### ISSUE THREAD

**Issue by edwardthehuman** [Paperback-iOS/extensions#89]
• readcomiconline.to

Would love to have that be added to the source so it’s just not going to be just manga, but comics/graphic novels as well.

**Comment by ConradWeiser** [comment]
ReadComicOnline is a cloudflare protected website. Paperback doesn't have the capability to act as a HTTP client which can get through Cloudflare. 

Unfortunately this website isn't currently possible :(

**Comment by edwardthehuman** [comment]
I see. I guess the next best thing would be ComicExtra right?

**Comment by ConradWeiser** [comment]
ComicExtra actually exists in a test repository! Contact me on Discord at VibrantClouds#1360 and I can help instruct you on getting access to the source.
(Note that you have to be a patreon until a public build supporting sources comes out)
