### ISSUE TITLE
[Suggestion] Purely English Manhwa Source

### ISSUE THREAD

**Issue by alone065** [Paperback-iOS/extensions#90]
I understand there are likely more things to be dealt with instead of this, so this is just merely a suggestion.
Currently, Manhwa18 exists as a source. Although it is fairly good, I am sure you are aware there are a mixture of Raw and Non-Raw Manhwa. I believe it could be beneficial to have another Manhwa source with only Non-Raw Manhwa. This is because those reading Raw's are part of a more niche group. Alongside this, Manhwa18 seems to also priorities updates with Raw's, leaving the Non-Raws behind. For these reasons, I feel it may prove useful to have another Manhwa source despite some possible repetition. 

A site which I think would fulfill this would be something like
- https://toonily.com/
But honestly anything else could work.

If you don't think this is necessary, feel free to close it.
Thanks

**Comment by ConradWeiser** [comment]
I think all of Manhwa18’s content is 18+ titles. Right away I see that this website has some Korean titles which are not such.

I recall back when Korean sources were being looked at, that the biggest concern was that some of the websites that came up really didn’t have much content as a whole.

Even the website that you linked on your issue, according to the listings, there is less than 200 titles over the whole website. Is this missing titles? Or is there really that number of translated manhwa available?

Is toonily in your opinion the best source for Korean material? Is there a better website out there?

I can certainly put toonily on my implement list if you feel it’s the best option here. Let me know what source you feel is the most ideal, and I’ll see what I can do.

**Comment by alone065** [comment]
Thanks for the response.
My reason for stating Toonily was that it tends to have quicker updates in comparison to other Korean Manhwa sites. That said, there is an underwhelming amount of content as you have pointed out, but having a source more targeted on speed isn’t inherently a bad thing?  Personally I think Toonily could be a pretty good addition, but I can understand why you are hesitant to do so.

**Comment by ConradWeiser** [comment]
You bring a good point. Paper mentioned that the source list will likely get categories as well, so if eventually there will just be a 'Manhwa' category, there's no harm in having a big source spread like you've mentioned.

Alright, I'll add this to the list! Keep a close eye on this issue, it will be updated as work gets done on it.
The source will likely show up in the Beta repository for a little while once it's worked on. Let me know if you have any more questions or concerns!

**Comment by ConradWeiser** [comment]
Toonily has been added to the h-extensions repository at https://github.com/Paperback-iOS/h-extensions due to a lot of the content being 18+
